// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Random = require("bs-platform/lib/js/random.js");
var MyConnect4$Game = require("./MyConnect4.bs.js");

function AIPlayer(MyGame) {
  var nextMove = function (s) {
    var legalMoves = Curry._1(MyGame.legalMoves, s);
    return List.nth(legalMoves, Random.$$int(List.length(legalMoves)));
  };
  return {
          PlayerGame: MyGame,
          nextMove: nextMove,
          playerName: ""
        };
}

var MyGame_stringOfPlayer = MyConnect4$Game.Connect4.stringOfPlayer;

var MyGame_stringOfState = MyConnect4$Game.Connect4.stringOfState;

var MyGame_stringOfMove = MyConnect4$Game.Connect4.stringOfMove;

var MyGame_initialState = MyConnect4$Game.Connect4.initialState;

var MyGame_legalMoves = MyConnect4$Game.Connect4.legalMoves;

var MyGame_gameStatus = MyConnect4$Game.Connect4.gameStatus;

var MyGame_nextState = MyConnect4$Game.Connect4.nextState;

var MyGame_moveOfString = MyConnect4$Game.Connect4.moveOfString;

var MyGame_estimateValue = MyConnect4$Game.Connect4.estimateValue;

var MyGame = {
  stringOfPlayer: MyGame_stringOfPlayer,
  stringOfState: MyGame_stringOfState,
  stringOfMove: MyGame_stringOfMove,
  initialState: MyGame_initialState,
  legalMoves: MyGame_legalMoves,
  gameStatus: MyGame_gameStatus,
  nextState: MyGame_nextState,
  moveOfString: MyGame_moveOfString,
  estimateValue: MyGame_estimateValue
};

function nextMove(s) {
  var legalMoves = Curry._1(MyConnect4$Game.Connect4.legalMoves, s);
  return List.nth(legalMoves, Random.$$int(List.length(legalMoves)));
}

var TestAIPlayer = {
  PlayerGame: MyGame,
  nextMove: nextMove,
  playerName: ""
};

var TestGame;

var MyAIPlayer = TestAIPlayer;

exports.AIPlayer = AIPlayer;
exports.TestGame = TestGame;
exports.TestAIPlayer = TestAIPlayer;
exports.MyAIPlayer = MyAIPlayer;
/* No side effect */
